apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-blue
  template:
    metadata:
      labels:
        app: frontend-blue
    spec:
      containers:
      - name: frontend-blue
        image: rameshkrishnannarakrish/reactprojectwebapp_frontendblue:{{ .Values.image.frontend-blue.tag }}
        ports:
        - containerPort: {{ .Values.service.frontend-blue.targetPort }}
        env:
          - name: API_BASE_URL
            value: "{{ .Values.env.API_BASE_URL }}"
        livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.frontend-blue.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.frontend-blue.port }}