apiVersion: v1
kind: Service
metadata:
  name: service1
  labels:
    app: service1
spec:
  selector:
    app: service1
  type: {{ .Values.service.service1.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.service1.port }}
      targetPort: {{ .Values.service.service1.targetPort }}