apiVersion: v1
kind: Service
metadata:
  name: service2-blue
  labels:
    app: service2-blue
spec:
  selector:
    app: service2-blue
  type: {{ .Values.service.service2_blue.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.service2_blue-blue.port }}
      targetPort: {{ .Values.service.service2_blue.targetPort }}