apiVersion: v1
kind: Service
metadata:
  name: service1-blue
  labels:
    app: service1-blue
spec:
  selector:
    app: service1-blue
  type: {{ .Values.service.service1_blue.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.service1_blue.port }}
      targetPort: {{ .Values.service.service1_blue.targetPort }}