apiVersion: v1
kind: Service
metadata:
  name: frontend-blue
  labels:
    app: frontend-blue
spec:
  selector:
    app: frontend-blue
  type: {{ .Values.service.frontend_blue.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.frontend_blue.port }}
      targetPort: {{ .Values.service.frontend_blue.targetPort }}