version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: scripts/install_helm.sh
      timeout: 300
      runas: root
    - location: scripts/pre_install_checks.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/helm_deploy.sh
      timeout: 300
      runas: ubuntu

  ValidateService:
    - location: scripts/validate.sh
      timeout: 300
      runas: root
