version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url
    GIT_TOKEN: /myapp/git-token
  variables:
    AWS_ACCOUNT_ID: "730335412393"
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies for frontend..."
      - cd frontend
      - npm install
      - npm audit fix --force
      - echo "Installing dependencies for service1..."
      - cd ../backend/service1
      - npm install
      - npm audit fix --force
      - echo "Installing dependencies for service2..."
      - cd ../service2
      - npm install
      - npm audit fix --force

  build:
    commands:
      - echo Building the application...
      - aws ecr-public get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin public.ecr.aws
      - echo Building the application...
      - docker build -t reactprojectwebapp_service2:$CODEBUILD_BUILD_NUMBER .
      - docker tag reactprojectwebapp_service2:$CODEBUILD_BUILD_NUMBER public.ecr.aws/l1b1a8r4/reactprojectwebapp_service2:$CODEBUILD_BUILD_NUMBER
      - docker push public.ecr.aws/l1b1a8r4/reactprojectwebapp_service2:$CODEBUILD_BUILD_NUMBER
      - echo Building the application...
      - cd ../service1
      - echo Building the application...
      - docker build -t reactprojectwebapp_service1:$CODEBUILD_BUILD_NUMBER .
      - docker tag reactprojectwebapp_service1:$CODEBUILD_BUILD_NUMBER public.ecr.aws/l1b1a8r4/reactprojectwebapp_service1:$CODEBUILD_BUILD_NUMBER
      - docker push public.ecr.aws/l1b1a8r4/reactprojectwebapp_service1:$CODEBUILD_BUILD_NUMBER
      - cd ../../frontend
      - echo Building the application...
      - docker build -t reactprojectwebapp_frontend:$CODEBUILD_BUILD_NUMBER .
      - docker tag reactprojectwebapp_frontend:$CODEBUILD_BUILD_NUMBER public.ecr.aws/l1b1a8r4/reactprojectwebapp_frontend:$CODEBUILD_BUILD_NUMBER
      - docker push public.ecr.aws/l1b1a8r4/reactprojectwebapp_frontend:$CODEBUILD_BUILD_NUMBER

  post_build:
    commands:
      - echo "Build completed successfully!"
      - echo Build completed on `date`
      - echo Updating Helm chart values with the new image tag...
      - cd ..
      - sed -i "s|tag:.*|tag:$CODEBUILD_BUILD_NUMBER|" helm/react-web-app-chart/values.yaml
      - git config --global user.email "codebuild@aws.com"
      - git config --global user.name "AWS Codebuild"
      - echo "https://$GIT_TOKEN@github.com" > ~/.git-credentials
      - git config --global credential.helper 'store'
      - git remote -v
      - git add helm/react-web-app-chart/values.yaml
      - git commit -m "Update tag in Helm chart"
      - git remote set-url origin https://$GIT_TOKEN@github.com/RameshKrishnanNaraKrish/react-project-webapp.git
      - git push origin main

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - 'node_modules/**/*'