version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url
    GIT_TOKEN: /myapp/git-token
    S3_BUCKET_NAME: /myapp/helms3bucket

source:
  version: "0.2"
  buildspec: "buildspec.yml"
  ignore:
    - "helm/react-web-app-chart/values.yaml"


phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Logging in to Docker registry...
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - IMAGE_TAG=${CODEBUILD_BUILD_NUMBER}
      - echo "Image_Tag:$IMAGE_TAG"

  build:
    commands:
      - echo Building the application...
      - cd backend/service2
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/reactprojectwebapp_service2${ENVIRONMENT}:$IMAGE_TAG" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/reactprojectwebapp_service2${ENVIRONMENT}:$IMAGE_TAG"
      - echo Building the application...
      - cd ../service1
      - echo Building the application...
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/reactprojectwebapp_service1${ENVIRONMENT}:$IMAGE_TAG" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/reactprojectwebapp_service1${ENVIRONMENT}:$IMAGE_TAG"
      - cd ../../frontend
      - echo Building the application...
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/reactprojectwebapp_frontend${ENVIRONMENT}:$IMAGE_TAG" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/reactprojectwebapp_frontend${ENVIRONMENT}:$IMAGE_TAG"

  post_build:
    commands:
      - echo "Build completed successfully!"
      - echo Build completed on `date`
      - echo Updating Helm chart values with the new image tag...
      - cd ..
      - echo $IMAGE_TAG
      - sed -i 's|tag:.*|tag:'"$IMAGE_TAG"'|' helm/react-web-app-chart/values.${ENVIRONMENT}.yaml
      - sed -i 's|tag:|tag:\ |' helm/react-web-app-chart/values.${ENVIRONMENT}.yaml
      - git config --global user.email "codebuild@aws.com"
      - git config --global user.name "AWS Codebuild"
      - echo "https://$GIT_TOKEN@github.com" > ~/.git-credentials
      - git config --global credential.helper 'store'
      - git remote -v
      - git add helm/react-web-app-chart/values.yaml
      - git commit -m "Update tag in Helm chart"
      - git remote set-url origin https://$GIT_TOKEN@github.com/RameshKrishnanNaraKrish/react-project-webapp.git
      - git push origin main
      - echo "Uploading Helm folder to S3..."
      - aws s3 cp helm/ s3://$S3_BUCKET_NAME/helm/ --recursive

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - 'node_modules/**/*'