# Frontend Deployment - Blue Version (frontend-blue.yaml)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      version: blue
  template:
    metadata:
      labels:
        app: frontend
        version: blue
    spec:
      containers:
      - name: frontend
        image: public.ecr.aws/l1b1a8r4/reactprojectwebapp_frontend:5  # Replace with your frontend Docker image
      imagePullSecrets:
      - name: myregistrykey
        ports:
        - containerPort: 80