# Frontend Service (frontend-service.yaml)
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-blue
spec:
  selector:
    app: frontend
    version: blue
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
