apiVersion: v1
kind: Service
metadata:
  name: frontend-green
  labels:
    app: frontend-green
spec:
  selector:
    app: frontend-green
  type: {{ .Values.service.frontend_green.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.frontend_green.port }}
      targetPort: {{ .Values.service.frontend_green.targetPort }}