apiVersion: v1
kind: Service
metadata:
  name: service1-green
  labels:
    app: service1-green
spec:
  selector:
    app: service1-green
  type: {{ .Values.service.service1-green.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.service1-green.port }}
      targetPort: {{ .Values.service.service1-green.targetPort }}