apiVersion: v1
kind: Service
metadata:
  name: service2-green
  labels:
    app: service2-green
spec:
  selector:
    app: service2-green
  type: {{ .Values.service.service2-green.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.service2-green.port }}
      targetPort: {{ .Values.service.service2-green.targetPort }}