# Service2 Service (service2-service.yaml)
apiVersion: v1
kind: Service
metadata:
  name: service2-service
spec:
  selector:
    app: service2
  ports:
    - port: 3002
      targetPort: 3002
  type: ClusterIP