# Frontend Deployment - green Version (frontend-blue.yaml)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      version: green
  template:
    metadata:
      labels:
        app: frontend
        version: green
    spec:
      containers:
      - name: frontend
        image: rameshkrishnannarakrish/reactprojectwebapp_frontend:3  # Replace with your frontend Docker image
      imagePullSecrets:
      - name: myregistrykey
        ports:
        - containerPort: 80