# Frontend Service (frontend-service.yaml)
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-green
spec:
  selector:
    app: frontend
    version: green
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
