apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing 
spec:
  ingressClassName: nginx
  rules:
  - host: myapp.orgramesh.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
  - host: service1.orgramesh.com
    http:
      paths:
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: service1
            port:
              number: 3001
  - host: service2.orgramesh.com
    http:
      paths:
      - path: /products
        pathType: Prefix
        backend:
          service:
            name: service2
            port:
              number: 3002
