apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: myapp.orgramesh.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
  - host: myapp.orgramesh.com
    http:
      paths:
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: service1
            port:
              number: 80
  - host: myapp.orgramesh.com
    http:
      paths:
      - path: /products
        pathType: Prefix
        backend:
          service:
            name: service2
            port:
              number: 80
