apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: rameshkrishnannarakrish/reactprojectwebapp_service1:v1
        ports:
        - containerPort: 3000
