apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: service2
        image: rameshkrishnannarakrish/reactprojectwebapp_service2:{{ .Values.image.service2.tag }}
        ports:
        - containerPort: {{ .Values.service.service2.targetPort }}
        env:
            - name: API_BASE_URL
              value: "{{ .Values.env.API_BASE_URL_PRODUCTS }}"
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.service2.port }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.service2.port }}
