apiVersion: v1
kind: Service
metadata:
  name: service2
  labels:
    app: service2
spec:
  selector:
    app: service2
  type: {{ .Values.service.service2.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.service2.port }}
      targetPort: {{ .Values.service.service2.targetPort }}