# Service2 Deployment - green Version (service2-green.yaml)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service2
      version: green
  template:
    metadata:
      labels:
        app: service2
        version: green
    spec:
      containers:
      - name: service2
        image: rameshkrishnannarakrish/reactprojectwebapp_service2:10342739826  # Replace with your service2 Docker image
        ports:
        - containerPort: 3002
