# Service2 Deployment - Blue Version (service2-blue.yaml)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service2
      version: blue
  template:
    metadata:
      labels:
        app: service2
        version: blue
    spec:
      containers:
      - name: service2
        image: rameshkrishnannarakrish/reactprojectwebapp_service2:1  # Replace with your service2 Docker image
      imagePullSecrets:
      - name: myregistrykey
        ports:
        - containerPort: 3002
