# Service1 Deployment - Blue Version (service1-blue.yaml)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service1
      version: blue
  template:
    metadata:
      labels:
        app: service1
        version: blue
    spec:
      containers:
      - name: service1
        image: public.ecr.aws/l1b1a8r4/reactprojectwebapp_service1:8  # Replace with your service1 Docker image
        ports:
        - containerPort: 3001
      env:
        # MySQL configuration for the app to connect to the MySQL service
        - name: DB_HOST
          value: "mysql-service"      # Internal service name for MySQL
        - name: DB_USER
          value: "root"               # MySQL root user
        - name: DB_PASSWORD
          value: "Test@123"           # MySQL root password
        - name: DB_NAME
          value: "reactwebapp"   
      readinessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
