# Service1 Deployment - green Version (service1-green.yaml)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service1
      version: green
  template:
    metadata:
      labels:
        app: service1
        version: green
    spec:
      containers:
      - name: service1
        image: public.ecr.aws/l1b1a8r4/reactprojectwebapp_service1:7  # Replace with your service1 Docker image
      imagePullSecrets:
      - name: myregistrykey
        ports:
        - containerPort: 3001
